replicaCount: 1

image:
  repository: registry.gitlab.com/mateoliverkovacs/demoapp/service
  pullPolicy: IfNotPresent
  tag: ""   

service:
  port: 8000
  nodePort: null

environment: ""

ingress:
  enabled: true
  host: myapp.local
  path: /
